apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: map-api-cnpe-prod

images:
  - name: map-api
    newTag: cnpe-prod

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: map-api
    path: ingress-host.patch.yaml
  - path: replicas.patch.yaml
